services:
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - backend_net

  api:
    image: nginx:alpine
    container_name: api
    networks:
      - backend_net

  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - backend_net

  worker:
    image: alpine:latest
    container_name: worker
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: sh -c "while true; do echo 'Trying to connect to 192.168.1.100:6379'; sleep 5; done"
    networks:
      - backend_net
    depends_on:
      - redis

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: secret
    networks:
      - backend_net

networks:
  redis_net:
    driver: bridge

  backend_net:
    driver: bridge

  frontend_net:
    driver: bridge
